[destination.bigquery]
location = "" # ADD GCS REGION FOR BIGQUERY (e.g. => "us-west1")

[destination.bigquery.credentials]
project_id = "" # ADD GCS PROJECT ID

# PASTE GCS SERVICE ACCOUNT KEY
private_key = ""

# ADD GCS SERVICE ACCOUNT EMAIL
client_email = ""