[destination.filesystem]
bucket_url = "gs://<URL>" # ADD GCS BUCKET URL

[destination.filesystem.credentials]
project_id = "" # ADD GCS PROJECT ID

# PASTE GCS SERVICE ACCOUNT KEY
private_key = ""

# ADD GCS SERVICE ACCOUNT EMAIL
client_email = ""